### ISSUE TITLE
Unable to enable FIPS mode on latest Node 18 LTS

### ISSUE THREAD

**Issue by elliot-huffman** [microsoftgraph/msgraph-sdk-javascript#1066]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Unable to make API requests when Node.JS FIPS mode is enabled.

**Console Errors:**
```
ChainedTokenCredential authentication failed.
CredentialUnavailableError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AggregateAuthenticationError: ChainedTokenCredential authentication failed.
CredentialUnavailableError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
    at C:\GitHub\**Redacted**\Server\node_modules\@azure\identity\dist\index.js:2657:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.withSpan (C:\GitHub\**Redacted**\Server\node_modules\@azure\identity\node_modules\@azure\core-tracing\dist\index.js:140:28)

Node.js v18.12.1
```

**Screenshots:**
![Screenshot of error in terminal](https://user-images.githubusercontent.com/5030490/198443706-9cf7d843-656b-431f-9ab6-69e62ca0472a.png)

## Steps to Reproduce

1. Enable FIPS mode in Node.JS (`crypto.setFips(true)`)
2. Make a call using the Graph SDK
3. Fails on request.

**Expected behavior:**
Works the same as when FIPS mode is not enabled (does not throw errors).

**Actual behavior:** [What actually happened]
After FIPS mode is enabled with `crypto.setFips(true)` the module is now unable to make Graph API requests.

## Additional Context

Ran issue with @Azure.Identity team (https://github.com/Azure/azure-sdk-for-js/issues/23633) but the issue is not with authentication as access token retrieval is successful and the only way to get an access token is to authenticate agains logon.microsoftonline.com and that is communicating successfully with the Auth Module.

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - 3.0.4

-   [X] Node (Check, if using Node version of SDK)

> Node Version - 18.12.1

**Comment by elliot-huffman** [comment]
@nikithauc , the link suggested isn't related to the issue I posted. Please see this ticket I had with the team:
https://github.com/Azure/azure-sdk-for-js/issues/23633. I proved that it was not the authentication library as I can get access tokens while in FIPS mode. I just can't call the Graph API.
