### ISSUE TITLE
Method .getStream doesn't support Promises

### ISSUE THREAD

**Issue by jmorino** [microsoftgraph/msgraph-sdk-javascript#110]
When trying to use the "Promise" syntax of the `.getStream` method (ie. with no callback),

```
client.api(url).getStream()
	.then(stream => {
		// do something with stream
	})
	.catch(err => {
		// do domething with err
	})
```

I get the following error:

```
TypeError: Cannot read property 'then' of undefined
```

Nevertheless, the"callback" syntax works great:
```
return new Promise((resolve, reject) => {
	client.api(url).getStream((err, stream) => {
		if (err) {
			// do domething with err
		}
		else {
			// do something with stream
		}
	});
});
```

**Comment by jmorino** [comment]
The same goes for the `.putStream` method:
```
client.api(url).putStream(buffer)
    .then(response => {
        // do something with response
    })
```
gives the following error:
```
TypeError: callback is not a function
    at Function.ResponseHandler.init (/.../node_modules/@microsoft/microsoft-graph-client/src/ResponseHandler.ts:6:13)
    at /.../node_modules/@microsoft/microsoft-graph-client/src/GraphRequest.ts:291:33
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by muthurathinam** [comment]
This is done in [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/105) and will be available in our next release.
