### ISSUE TITLE
GraphError: Subscription validation request failed despite Accessible Endpoint hosted on Google Cloud

### ISSUE THREAD

**Issue by kiritowu** [microsoftgraph/msgraph-sdk-javascript#1472]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I've been working on implementing Microsoft Graph webhook subscriptions in my application, and I've run into an issue with subscription validation. Whenever I attempt to validate the subscription, I've consistently receive the following error message:

`GraphError: Subscription validation request timed out.`

My subscription server is deployed and hosted on Google Cloud Function v2, allowing all unauthenticated invocations. 

The following verification is performed using [Microsoft's Postman Collection](https://learn.microsoft.com/en-us/graph/use-postman):
- Endpoint is accessible on the internet with unauthenticated invocation
- Endpoint is returning 200OK, text-plain, decoded validationToken as intended
- Endpoint able to reply within 10s timeframe consistently

However, when I actually attempt to create subscription request using MicrosoftGraph Javascript SDK, the validation request always faces timeout issue despite it being accessible via PostMan.

**Code Snippet to Invoke Subscription Request**

```typescript
const requestBody: Subscription =
        changeType: "updated",
        resource: `/users/${folderId}/drive/root
        expirationDateTime: new Date(now.setDate(now.getDate() + 28)).toISOString(),
        notificationUrl: `${process.env.ONEDRIVE_URL}/folders/${folderId}?workspaceId=${workspaceId}`,
        clientState: "somerandomtext";
      }

await driveClient.api("/subscriptions").post(requestBody);
```

**Console Errors:**
```
GraphError: Subscription validation request timed out.
    at new GraphError (/code/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:34:28)
    at GraphErrorHandler.constructErrorFromResponse (/code/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:63:22)
    at Function.<anonymous> (/code/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:91:48)
    at step (/code/node_modules/tslib/tslib.js:195:27)
    at Object.next (/code/node_modules/tslib/tslib.js:176:57)
    at /code/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/code/node_modules/tslib/tslib.js:165:16)
    at GraphErrorHandler.getError (/code/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (/code/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:315:84) {
  statusCode: 400,
  code: 'InvalidRequest',
  requestId: 'uuid,
  date: 2023-09-30T21:36:48.000Z,
  body: '{"code":"InvalidRequest","message":"Subscription validation request timed out.","innerError":{"date":"2023-10-01T05:36:48","request-id":"uuid,"client-request-id":"uuid}}',
  headers: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(10) {
      'cache-control' => [Object],
      'transfer-encoding' => [Object],
      'content-type' => [Object],
      'content-encoding' => [Object],
      'vary' => [Object],
      'strict-transport-security' => [Object],
      'request-id' => [Object],
      'client-request-id' => [Object],
      'x-ms-ags-diagnostic' => [Object],
      'date' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}

```
**Code Snippet to Listen for Subscription Validation**
```typescript
import { FastifyPluginAsyncTypebox } from "@fastify/type-provider-typebox";

import { Type } from "@sinclair/typebox";

export const ParamsSchema = Type.Object({
  fid: Type.String(),
});

export const QuerySchema = Type.Object({
  workspaceId: Type.RegEx(/^[0-9a-z]{25}$/),
  validationToken: Type.Optional(Type.String()),
});


const main: FastifyPluginAsyncTypebox = async (app, options): Promise<void> => {
  /**
   * Listens to changes to a folder
   */
  app.post("/", { schema: { params: ParamsSchema, querystring: QuerySchema } }, async (req, rep) => {
    app.log.info("Received webhook request");
    // If there is a validationToken parameter
    // in the query string, this is the endpoint validation
    // request sent by Microsoft Graph. Return the token
    // as plain text with a 200 response
    // https://docs.microsoft.com/graph/webhooks#notification-endpoint-validation
    // https://github.com/microsoftgraph/nodejs-webhooks-sample/blob/main/routes/listen.js#L13
    if (req.query.validationToken) {
      return req.query.validationToken;
    }

    // Other logic but is commented
    return {};
  });
}
```

**Screenshots:** [If applicable, add screenshots to help explain your problem]
![verification-of-postman](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/70313929/4f2e4260-beae-4461-84f2-bded2f6c4408)

**Logs from Google Cloud Console**
![Screenshot from 2023-10-01 14-37-55](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/70313929/2770fb89-6e75-4e37-aed7-c282cf6dc054)

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - 3.0.7

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v18.17.1

I'm unsure why the validation request fails in my application but works with Postman. Can anyone offer guidance on what could be causing this issue or suggest potential solutions?

**Comment by sebastienlevert** [comment]
That's a good question. Can you run it locally via Dev Tunnels or ngrok? Can you create your subscription via Postman vs. just calling your validation endpoint? This would also be helpful. Thanks!

**Comment by nilooy** [comment]
is there any solution for this? i'm having same issue

**Comment by LuanFernandes23** [comment]
Facing the same issue, any solution?
