### ISSUE TITLE
Call to POST /trustFramework/keySets/{id}/uploadSecret endpoint results to Error: There is a problem with the Service

### ISSUE THREAD

**Issue by rjdecilos** [microsoftgraph/msgraph-sdk-javascript#1547]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Trying to upload a secret using the POST/trustFramework/keySets/{id}/uploadSecret endpoint results to Error: There is a problem with the Service, using this sdk.

**Console Errors:**

Error in console below:
Error: There is a problem with the service.125    at GraphError (...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphError.js:34:28)126    at Function.GraphErrorHandler2.constructErrorFromResponse (...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:63:22)127    at Function.<anonymous> (...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:91:48)128    at step (...\node_modules\tslib\tslib.js:195:27)129    at Object.next, Opens in a new window (...\node_modules\tslib\tslib.js:176:57)130    at <anonymous> (...\node_modules\tslib\tslib.js:169:75)131    at new Promise (<anonymous>)132    at Object.__awaiter (...\node_modules\tslib\tslib.js:165:16)133    at Function.GraphErrorHandler2.getError (...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:87:24)134    at GraphRequest2.<anonymous> (...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js:315:84)135    at step (...\node_modules\tslib\tslib.js:195:27)136    at Object.throw (...\node_modules\tslib\tslib.js:176:57)137    at rejected (...\node_modules\tslib\tslib.js:167:68)138    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Create keyset
```
const newKeyData = {
    id: name,
    kty: 'oct',
    use: "sig",
    nbf: startDateTimeTimestamp,
    exp: expirationTimestamp,
  };
  await graphclient.api('/trustFramework/keySets').version('beta').post(newKeyData);
```
2. upload secret in KeySet
```
  const keyData = {
    use: "sig",
    k: secret,
    nbf: startDateTimestamp,
    exp: expirationTimestamp,
  };
  await graphclient.api(`/trustFramework/keySets/${id}/uploadSecret`).version('beta').post(keyData);
```

**Expected behavior:** Secret to be successfully uploaded in the policy key

**Actual behavior:** microsoft-graph-client is throwing an Error

## Additional Context

There needs to be an Azure AD B2C tenant to test this specific endpoints

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - 3.0.7

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v18.18.0

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - Edge

> Version - 119.0.2151.93

**Comment by rjdecilos** [comment]
I was using Date.parse("date value") as the value for the exp field, but this wasn't consistent with unix timestamp value, after fixing the exp field to use unix timestamp, this was fixed.

In summary, please divide Date.parse() value to 1000 for timestamp field values:
`exp: Date.parse('insert date here') / 1000`
