### ISSUE TITLE
ErrorCode: CultureNotFoundException, Message: Culture is not supported

### ISSUE THREAD

**Issue by NWH-SAmin5** [microsoftgraph/msgraph-sdk-javascript#1839]
### Describe the bug

I am calling Privileged Identity Management API and receiving this error

```typescript
return await this._graphClient
            .api('/roleManagement/directory/roleEligibilitySchedules/filterByCurrentUser(on=\'principal\')')
            .get().then((res) => {
                return res.value;
            });
```

```
{"ErrorCode":"CultureNotFoundException","Message":"Culture is not supported.\r\nParameter name: name\r\n* is an invalid culture identifier.","Target":null,"Details":null,
"InnerError":null,"InstanceAnnotations":[],"TypeAnnotation":null}
```

I have tried other APIs in the Microsoft Graph, they are fine. Get this error only for Privileged Identity Management API so far.

### Expected behavior

Sample response

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#roleManagement/directory/roleEligibilitySchedules",
    "value": [
        {
            "id": "77f71919-62f3-4d0c-9f88-0a0391b665cd",
            "principalId": "071cc716-8147-4397-a5ba-b2105951cc0b",
            "roleDefinitionId": "8424c6f0-a189-499e-bbd0-26c1753c96d4",
            "directoryScopeId": "/",
            "appScopeId": null,
            "createdUsing": "77f71919-62f3-4d0c-9f88-0a0391b665cd",
            "createdDateTime": "2022-04-12T14:44:50.287Z",
            "modifiedDateTime": "0001-01-01T08:00:00Z",
            "status": "Provisioned",
            "memberType": "Direct",
            "scheduleInfo": {
                "startDateTime": "2022-04-12T14:44:50.287Z",
                "recurrence": null,
                "expiration": {
                    "type": "afterDateTime",
                    "endDateTime": "2024-04-10T00:00:00Z",
                    "duration": null
                }
            }
        }
    ]
}
```

### How to reproduce

Install using this links

[Microsoft Graph JavaScript Client Library](https://github.com/microsoftgraph/msgraph-sdk-javascript?tab=readme-ov-file#microsoft-graph-javascript-client-library)
[Installation](https://github.com/microsoftgraph/msgraph-sdk-javascript?tab=readme-ov-file#installation)
[Via npm](https://github.com/microsoftgraph/msgraph-sdk-javascript?tab=readme-ov-file#via-npm)

Call this 

```typescript
return await this._graphClient
            .api('/roleManagement/directory/roleEligibilitySchedules/filterByCurrentUser(on=\'principal\')')
            .get().then((res) => {
                return res.value;
            });
```

### SDK Version

3.0.7

### Debug output

```
GraphError: {"ErrorCode":"CultureNotFoundException","Message":"Culture is not supported.\r\nParameter name: name\r\n* is an invalid culture identifier.","Target":null,"Details":null,"InnerError":null,"InstanceAn
notations":[],"TypeAnnotation":null}
      at new GraphError (E:\...\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:63:3)
      at Function.GraphErrorHandler.constructErrorFromResponse (E:\...\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:77:18)
      at Function.<anonymous> (E:\...\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:104:31)
      at step (E:\...\node_modules\tslib\tslib.js:196:27)
      at Object.next (E:\...\node_modules\tslib\tslib.js:177:57)
      at E:\...\node_modules\tslib\tslib.js:170:75
      at new Promise (<anonymous>)
      at Object.__awaiter (E:\...\node_modules\tslib\tslib.js:166:16)
      at Function.GraphErrorHandler.getError (E:\...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:87:24)
      at GraphRequest.<anonymous> (E:\...\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:391:55)
```

### Configuration
Windows Server 2019
NodeJS app v18.17.1
Typescript

**Comment by NWH-SAmin5** [comment]
In package.json added this parameter to the node command `--no-experimental-fetch`

**Comment by NWH-SAmin5** [comment]
It works after adding this parameter to the node command --no-experimental-fetch in package.json

**Comment by Abdulrahmanelheyb** [comment]
I solved this issue by adding Accept-Language header to the request you can try it, It works with me
