### ISSUE TITLE
ClientConfigurationError: The cache location provided is not valid. Provided value: sessionStorage. Possible values are: localStorage, sessionStorage.

### ISSUE THREAD

**Issue by JYC-99** [microsoftgraph/msgraph-sdk-javascript#264]
# Bug Report

## Prerequisites

-   [ ] Can you reproduce the problem?
-   [ ] Are you running the latest version?
-   [ ] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I'm following the getting started document. But it does not work and I got the error: 

**Console Errors:**

```
 throw ClientConfigurationError_1.ClientConfigurationError.createInvalidCacheLocationConfigError(this.config.cache.cacheLocation);
            ^

ClientConfigurationError: The cache location provided is not valid. Provided value: sessionStorage. Possible values are: localStorage, sessionStorage.
    at ClientConfigurationError.AuthError [as constructor] (D:\codebase\workspace-portal\node_modules\msal\lib-commonjs\error\AuthError.js:18:28)
    at ClientConfigurationError.ClientAuthError [as constructor] (D:\codebase\workspace-portal\node_modules\msal\lib-commonjs\error\ClientAuthError.js:93:28)
    at new ClientConfigurationError (D:\codebase\workspace-portal\node_modules\msal\lib-commonjs\error\ClientConfigurationError.js:82:28)
    at Function.ClientConfigurationError.createInvalidCacheLocationConfigError (D:\codebase\workspace-portal\node_modules\msal\lib-commonjs\error\ClientConfigurationError.js:91:16)
    at new UserAgentApplication (D:\codebase\workspace-portal\node_modules\msal\lib-commonjs\UserAgentApplication.js:98:71)
    at Object.<anonymous> (D:\codebase\workspace-portal\apps\portal\tests-e2e\image-diff\mailer.js:19:25)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
  errorCode: 'invalid_cache_location',
  errorMessage: 'The cache location provided is not valid. Provided value: sessionStorage. Possible values are: localStorage, sessionStorage.',
  name: 'ClientConfigurationError'
```

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

```
require("isomorphic-fetch");
const { UserAgentApplication } = require("msal");
const { Client } = require("@microsoft/microsoft-graph-client");
const {
  ImplicitMSALAuthenticationProvider
} = require("@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider");

// An Optional options for initializing the MSAL @see https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#configuration-options
const msalConfig = {
  auth: {
    clientId: "", // Client Id of the registered application. I removed it in this issue report.
    redirectUri: "" // I removed it in this issue report.
  }
};
const graphScopes = ["user.read", "mail.send"]; // An array of graph scopes

// Important Note: This library implements loginPopup and acquireTokenPopup flow, remember this while initializing the msal
// Initialize the MSAL @see https://github.com/AzureAD/microsoft-authentication-library-for-js#1-instantiate-the-useragentapplication
const msalApplication = new UserAgentApplication(msalConfig);
const options = new MicrosoftGraph.MSALAuthenticationProviderOptions(graphScopes);
const authProvider = new ImplicitMSALAuthenticationProvider(msalApplication, options);
const client = Client.initWithMiddleware({
  authProvider // An instance created from previous step
});

async function sendEmail() {
  try {
    let userDetails = await client.api("/me").get();
    console.log(userDetails);
  } catch (error) {
    throw error;
  }
}

sendEmail();

```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - ^2.0.0

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v12.14.1

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by darrelmiller** [comment]
Unfortunately the ImplicitMSALAuthenticationProvider does not work in Node.js.  You will need to use some other OAuth2 library and implement an IAuthenticationProvider.  There is an issue on this topic over in the MSAL repo. https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1189
