### ISSUE TITLE
Running Node.js app fails with "Cannot find module 'es6-promise'"

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-javascript#34]
After installing the SDK via NPM into a Node.js web app, when I run the app from the command line I get:

```
Error: Cannot find module 'es6-promise'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jasonjoh\Source\Repos\node.js\node-tutorial\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js:5:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jasonjoh\Source\Repos\node.js\node-tutorial\node_modules\@microsoft\microsoft-graph-client\lib\src\index.js:4:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-tutorial@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-tutorial@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-tutorial
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-tutorial
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jasonjoh\Source\Repos\node.js\node-tutorial\npm-debug.log
```

Installing `es6-promise` manually via npm fixes this. However, you should have this listed as a dependency in your package.json. It's currently only listed under `devDependencies`.

**Comment by dan-silver** [comment]
Thanks, I agree this should be in dependencies not devDependencies. Fixed in version 0.4.1
