### ISSUE TITLE
After updating to version 2.1.0 - getting goups transitivmeberof by email throws an error

### ISSUE THREAD

**Issue by rudxde** [microsoftgraph/msgraph-sdk-javascript#350]
# Bug Report

## Prerequisites

-   [ x] Can you reproduce the problem?
-   [ x] Are you running the latest version?
-   [ x] Are you reporting to the correct repository?
-   [x ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug or feature]

**Console Errors:** [Is there any console error]

```
Error: Resource '<Group mail address>' does not exist or one of its queried reference-property objects are not present.
    at new GraphError (/usr/src/app/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:31:28)
    at Function.GraphErrorHandler.constructErrorFromResponse (/usr/src/app/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:61:22)
    at Function.<anonymous> (/usr/src/app/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:92:48)
    at step (/usr/src/app/node_modules/tslib/tslib.js:139:27)
    at Object.next (/usr/src/app/node_modules/tslib/tslib.js:120:57)
    at /usr/src/app/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:109:16)
    at Function.GraphErrorHandler.getError (/usr/src/app/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (/usr/src/app/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:305:84) {
  statusCode: 404,
  code: 'Request_ResourceNotFound',
  requestId: 'a0d54f1a-1a7f-4b91-9fba-5614bcac0c0a',
  date: 2020-11-08T14:56:04.000Z,
  body: `{"code":"Request_ResourceNotFound","message":"Resource '<Group mail address>' does not exist or one of its queried reference-property objects are not present.","innerError":{"date":"2020-11-08T14:56:04","request-id":"a0d54f1a-1a7f-4b91-9fba-5614bcac0c0a","client-request-id":"47dff086-40fe-aea8-0b23-304ba78c0b3d"}}`
```

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

**Expected behavior:** 
(works in version 2.0.0)
Should return the desired group

**Actual behavior:** 

throws 404 error

## Additional Context
code:

```ts
let userGroups: GraphInterfaces.IMemberResult = await graphClient.api(`/users/${email}/transitiveMemberOf`).get();
```

Add any other context about the problem here..

## Usage Information

SDK Version - [SDK version you are using]

-   [ x] Node (Check, if using Node version of SDK)

> Node Version - 12

**Comment by nikithauc** [comment]
@rudxde  Thank you for reporting this issue! I will look into this issue

**Comment by nikithauc** [comment]
@rudxde. Can I please get some more information of the application you are using? Information such as JavaScript framework used, the environment the application runs in( Node or browser?), Node version in use, browser name and version. Basically, any information that will help in reproducing this issue?

**Comment by rudxde** [comment]
node 12 with typescript 4

this is how i initialize the client:
```
import 'isomorphic-fetch';
import { Client } from '@microsoft/microsoft-graph-client';
import { AccessToken } from 'simple-oauth2';

export function getAuthenticatedGraphClient(accessToken: AccessToken): Client {
    return Client.init({
        authProvider: (done) => {
            done(null, accessToken.token.access_token);
        },
    });
}
```

The authentication is going against a organization with a api token

**Comment by MIchaelMainer** [comment]
The console error you provided with requestId = `a0d54f1a-1a7f-4b91-9fba-5614bcac0c0a` was for a request that looked like:
GET https://graph.microsoft.com/v1.0/users/{someId}/transitivemembersof

The example:
```
let group: GraphInterfaces.IMemberResult = await graphClient
        .api(`/groups/`)
        .query({$filter: `mail+eq+'${groupEmail}'`})
        .get();
```
does not produce that error message, or at least we can't reproduce it. Can you provide a error requestId for the groups filter error?

**Comment by rudxde** [comment]
oh my mistake, there was a other request, which produced the error. Its, like you said an transitivmemberof request:
```ts
let userGroups: GraphInterfaces.IMemberResult = await graphClient.api(`/users/${email}/transitiveMemberOf`).get();
```

**Comment by nikithauc** [comment]
@rudxde 
The error 'Resource <groupEmail>does not exist or one of its queried reference-property objects are not present.' occurs when the mail is not valid that is not present in the user's list. I am able to reproduce this error by passing an invalid mail in the query. 

`/users/${groupEmail}/transitiveMemberOf` works if the mail is a valid one and present in the user's list.

**Comment by rudxde** [comment]
The problem ist, that this rescouce exsists. The error is not thrown, when i am using the previous minor version.

**Comment by nikithauc** [comment]
@rudxde  Can you please tell me if you see a difference in the request URL that is being made to the Graph API for '/users/${groupEmail}/transitiveMemberOf' between 2.0.0 and 2.1.0?

**Comment by nikithauc** [comment]
Closing this due to inactivity.
