### ISSUE TITLE
 "Complex query on property ... is not supported" for filter clause working on Graph Explorer

### ISSUE THREAD

**Issue by kwv** [microsoftgraph/msgraph-sdk-javascript#355]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug or feature]

complex filter that works in [Graph Explorer ](https://developer.microsoft.com/en-us/graph/graph-explorer?request=applications%3F%24filter%3DrequiredResourceAccess%2Fany(c%3Ac%2FresourceAppId%20eq%20'00000003-0000-0000-c000-000000000000')%20or%20%20requiredResourceAccess%2Fany(c%3Ac%2FresourceAppId%20eq%20'00000003-0000-0000-c000-000000000000')%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d) 
`https://graph.microsoft.com/v1.0/applications?$filter=requiredResourceAccess/any(c:c/resourceAppId eq '00000003-0000-0000-c000-000000000000') or  requiredResourceAccess/any(c:c/resourceAppId eq '00000003-0000-0000-c000-000000000000')&$count=true`

`https://graph.microsoft.com/v1.0/applications?$filter=requiredResourceAccess/any(c:c/resourceAppId eq '***')&$count=true`

throws an error in msgraph-sdk-javascript
"code":"Request_UnsupportedQuery","message":"Complex query on property requiredResourceAccess is not supported."

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce
```
  const response: PageCollection = await client
    .api(`/applications`)
    .query(`$filter=requiredResourceAccess/any(c:c/resourceAppId eq '00000003-0000-0000-c000-000000000000') `)
    // also tried this syntax
    //.filter("requiredResourceAccess/any(c:c/resourceAppId eq '00000003-0000-0000-c000-000000000000')")
    .count(true)
    .get();
```

**Expected behavior:** [What you expected to happen]
response payload as from MS Graph Explorer 
`https://graph.microsoft.com/v1.0/applications?$filter=requiredResourceAccess/any(c:c/resourceAppId eq '00000003-0000-0000-c000-000000000000')&$count=true `

**Actual behavior:** [What actually happened]
```
GraphError: Complex query on property requiredResourceAccess is not supported.
    at new GraphError (/Users/project/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:31:28)
    at Function.GraphErrorHandler.constructErrorFromResponse (/Users/project/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:61:22)
    at Function.<anonymous> (/Users/project/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:92:48)
    at step (/Users/project/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/project/node_modules/tslib/tslib.js:122:57)
    at /Users/project/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/project/node_modules/tslib/tslib.js:111:16)
    at Function.GraphErrorHandler.getError (/Users/project/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:88:24)
    at GraphRequest.<anonymous> (/Users/project/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:305:84) {
  statusCode: 400,
  code: 'Request_UnsupportedQuery',
  requestId: 'd15ab3c0-0347-4748-8775-7314034503ca',
  date: 2020-11-13T02:51:07.000Z,
  body: '{"code":"Request_UnsupportedQuery","message":"Complex query on property requiredResourceAccess is not supported.","innerError":{"date":"2020-11-12T20:51:07","request-id":"d15ab3c0-0347-4748-8775-7314034503ca","client-request-id":"8611611d-c8de-33c6-9144-4e4bcdc1a801"}}'
```
## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - 2.0.0/2.1.1

-   [X] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by kwv** [comment]
Curious if it's this

https://developer.microsoft.com/en-us/graph/blogs/build-advanced-queries-with-count-filter-search-and-orderby/

I notice when removing `ConsistencyLevel` header in msgraph explorer get the same result.


is there a way to override the headers on the request ?

**Comment by kwv** [comment]
Setting this addresses the issue 

```typescript

  const clientOptions: ClientOptions = {
    fetchOptions: { headers: { ConsistencyLevel: 'eventual' } },
  };
```
