### ISSUE TITLE
Cannot read property 'request-id' of undefined

### ISSUE THREAD

**Issue by moasakthi** [microsoftgraph/msgraph-sdk-javascript#75]
I've been trying to use the following code:
` let token = await getAccessToken(authData),
    auth_data = token.token,
    isRefresh = token.isRefresh;
  if (auth_data.access_token) {
    const client = graph.Client.init({
      authProvider: (done) => {
        done(null, auth_data.access_token);
      }
    });
    let url = `https://outlook.office.com/api/v2.0/me/calendars/${id.id}/events`
    const result = await client
      .api(url)
      .post(event, (err, res) => {
        console.log(res);
        return cb(res)
      })
  } else {
    return null;
  }`

To create events i am trying something like above, some of the events created. for some events, it showing like below, it stops the process.
`C:\Users\Siva Sakthi Velan R\Desktop\CoE Projects\ThenHow\GitLab\then-how\node_modules\@microsoft\microsoft-graph-client\lib\src\ResponseHandler.js:48
            requestId: errObj.innerError["request-id"],
                                        ^

TypeError: Cannot read property 'request-id' of undefined
    at Function.ResponseHandler.ParseError (C:\project\node_modules\@microsoft\microsoft-graph-client\lib\src\ResponseHandler.js:48:41)
    at Function.ResponseHandler.init (C:\project\node_modules\@microsoft\microsoft-graph-client\lib\src\ResponseHandler.js:14:42)
    at C:\project\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js:191:55
    at Request.callback (C:\project\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\project\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\project\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

I don't even understand, why its keeps coming. I can't debug myself, because i newbie in this. 

Can you please help me out in this ?

**Comment by MIchaelMainer** [comment]
You are trying to post to 

`let url = 'https://outlook.office.com/api/v2.0/me/calendars/${id.id}/events'`

The Outlook specific endpoint has been deemphasized. This is the Microsoft Graph client library. Please change that line to:

`//The following line gets posted to https://graph.microsoft.com/v1.0/`
`let url = 'me/calendars/${id.id}/events'`

Are you getting a token for Microsoft Graph or for Exchange?

**Comment by moasakthi** [comment]
@MIchaelMainer yes i am using Microsoft Graph for getting token. I tried with changing url like you mentioned above: it show `'InvalidAuthenticationToken'` . full error below

```  
{ statusCode: 401,
  code: 'InvalidAuthenticationToken',
  message: 'CompactToken parsing failed with error code: 8004920A',
  requestId: 'd7d69457-e15f-4ee6-945b-990c1ba95787',
  date: 2018-05-22T11:07:35.974Z,
  body:
   { code: 'InvalidAuthenticationToken',
     message: 'CompactToken parsing failed with error code: 8004920A',
     innerError:
      { 'request-id': 'd7d69457-e15f-4ee6-945b-990c1ba95787',
        date: '2018-05-22T11:07:37' } } }
```

**Comment by MIchaelMainer** [comment]
What resource is the registered application trying to access? Microsoft Graph or Microsoft Exchange Online. 
 
Either:
1) Inspect the access token and show me the resource.
2) Can you share with me how you registered your application?
